# Generated by Django 4.1.5 on 2023-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=25)),
                ('tipo_de_usuario', models.CharField(choices=[('PS', 'psicologo'), ('PA', 'paciente')], max_length=2)),
            ],
        ),
    ]
