# Generated by Django 4.1.5 on 2023-01-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0002_paciente_psicologo_ubicacion_recomendacion_educacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologos.paciente'),
        ),
    ]
