# Generated by Django 4.1.5 on 2023-01-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0003_alter_cita_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='recomendacion',
            field=models.CharField(default='Recomendacion', max_length=150),
        ),
    ]
